"""
models.py — Inbox Zero data models
All email I/O flows through these Pydantic models.
"""

from pydantic import BaseModel, Field
from typing import Optional, List, Literal
from datetime import datetime
from enum import Enum


class PriorityLevel(str, Enum):
    URGENT = "urgent"
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"
    UNSUB = "unsubscribe_candidate"


class EmailAction(str, Enum):
    LABEL = "label"
    ARCHIVE = "archive"
    DRAFT_REPLY = "draft_reply"
    FLAG_URGENT = "flag_urgent"
    MARK_UNSUB = "mark_unsubscribe"
    SUMMARIZE = "summarize"
    NO_ACTION = "no_action"


class EmailSummary(BaseModel):
    """Compact representation passed to Claude — keeps token count low."""
    message_id: str
    thread_id: str
    sender: str
    sender_email: str
    subject: str
    date: datetime
    snippet: str                     # First 200 chars
    body_preview: str                # First 500 chars of full body
    has_attachments: bool = False
    is_reply: bool = False
    thread_length: int = 1


class TriageResult(BaseModel):
    """Claude's triage decision for a single email."""
    message_id: str
    subject: str
    sender_email: str
    priority: PriorityLevel
    labels: List[str]
    actions: List[EmailAction]
    reasoning: str                   # One sentence — why this priority
    draft_needed: bool = False
    draft_context: Optional[str] = None   # What the draft should cover
    unsub_candidate: bool = False


class DraftReply(BaseModel):
    """A draft reply generated by Claude."""
    message_id: str
    thread_id: str
    subject: str
    to: str
    body: str                        # Ready to send — no placeholders
    word_count: int
    tone_check: str                  # "direct" | "warm" | "formal"


class DigestEntry(BaseModel):
    """Single email entry in the daily digest."""
    subject: str
    sender: str
    priority: PriorityLevel
    one_line_summary: str
    action_needed: Optional[str] = None


class DailyDigest(BaseModel):
    """Full daily digest report."""
    date: datetime
    total_processed: int
    urgent_count: int
    action_required: List[DigestEntry]
    job_opportunities: List[DigestEntry]
    to_read: List[DigestEntry]
    unsub_candidates: List[DigestEntry]
    already_handled: int             # Count archived/labeled with no action needed
    digest_text: str                 # Full Claude-generated narrative summary


class UnsubscribeTarget(BaseModel):
    """Email identified for unsubscribe or bulk delete."""
    sender_email: str
    sender_name: str
    subject_pattern: str
    message_ids: List[str]           # All messages from this sender
    recommended_action: Literal["unsubscribe", "bulk_delete", "block"]
    reason: str
